[workspace]
members = ["app", "core", "data", "server"]
resolver = "3"

[workspace.dependencies]
wabble-core = { path = "core" }
anyhow = "1.0.100"
bincode = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
zstd = "0.13.3"
